### ISSUE TITLE
Missing materials for dragon and absolute paths in material file

### ISSUE THREAD

**Issue by zero-to-hero-books** [monstrobishi/xeffects#1]
Just wanted to let you know that the dragon model is missing the .jpg files referenced in the material file.
Also, the file paths in the material file are absolute paths, so even if you include the images the materials won't be found. Lines 56-58 in dragon.mtl:
map_Kd d:\a-turbo-squid\dragon\lw\d-top-view.jpg
map_d d:\a-turbo-squid\dragon\lw\wings-trans.jpg
map_bump -bm 0.0416667 d:\a-turbo-squid\dragon\lw\d-side-view.jpg

**Comment by monstrobishi** [comment]
Hi co3cssui,

Thanks for your comment. I think the dragon is intentionally used without textures. I didn't read the dragon.mtl file thoroughly at the time I created this library so I didn't know it even had textures included.

Cheers,
